### ISSUE TITLE
Chapter 5 Sample project is 3 versions behind ios 15. Project will not event build on M1 Pro Apple silicon chip. 

### ISSUE THREAD

**Issue by erikuecke** [Apress/Mastering-ARKit#1]
Chapter 5 Sample project is 3 versions behind ios 15. Project will not event build on M1 Pro Apple silicon chip. 

How old is this code?

Getting Errors related to project unable to see Main.storyboard and LaunchScreen.storyboard:

Build input file cannot be found: '/Users/erikuecke/iosDevelopment/MasterARKit/Mastering-ARKit-main/5/Final/ARKit3DDemo/Base.lproj/Main.storyboard'

Build input file cannot be found: '/Users/erikuecke/iosDevelopment/MasterARKit/Mastering-ARKit-main/5/Final/ARKit3DDemo/Base.lproj/LaunchScreen.storyboard'

**Comment by jayvenn** [comment]
@erikuecke 
I've reindexed the chapter 5 project source code, essentially creating a new project and pulling in the files, and should be good to go now.

**Comment by jayvenn** [comment]
There seems to be a problem with the chapters' source code upload. I'm taking a look at them beyond chapter 5.
