### ISSUE TITLE
Chapter 6: Boat usdz object needs to be resized

### ISSUE THREAD

**Issue by erikuecke** [Apress/Mastering-ARKit#3]
Readers should probably be instructed to resize the Boat.usdz file either from the SceneKit Node Instspecter menu or programattically in the func addBoatToSceneView(location: CGPoint) method. 
Current size of boat file renders around user because of size. 

`boatReferenceNode.scale = SCNVector3(x: 0.001, y: 0.001, z: 0.001)`

**Comment by jayvenn** [comment]
@erikuecke 
For chapter 6, updated **boat.usdz**'s parent node using the Inspector menu to 0.001 for x, y, and z.
Thank you for the feedback! :]
