### ISSUE TITLE
Chapert 08 - Section: Testing Light Properties - Unhide main stack view to see sliders. 

### ISSUE THREAD

**Issue by erikuecke** [Apress/Mastering-ARKit#5]
Hello Fellow Readers 

To see the sliders you will need to unhide the "Main Stack View" from the attributes inspector which can be accessed from the Main.storyboard. 

Happy Sliding! 👨🏻‍💻

**Comment by jayvenn** [comment]
@erikuecke 
Appreciate the feedback and details, might have found a potential technical editor for the next book! ;)
