### ISSUE TITLE
Chapter 13 - Captilize filename for audio source. 

### ISSUE THREAD

**Issue by erikuecke** [Apress/Mastering-ARKit#7]
Hello fellow readers. 

Make sure to captilize the filename for your audio source file to match the audio file name, if your not hearing the lion roar. 

"Lion-stereo.mp3"

**Comment by jayvenn** [comment]
@erikuecke Thanks for pointing this out. Updated Chapter 13's audio file names from "Lion-stereo.mp3" to "lion-stereo.mp3" for matching the book's text.
